// src/store.js
// Centralized global state.
export const state = {
  S: [],
  items: [],
  _filteredItems: [],
  _itemPage: 0,
  _itemsPerPage: 200,
  _sortCol: null,
  _sortDir: 1,
  _isDragging: false,
  _sortKeyMap: { code:'code', name:'name', grp:'grp', batch:'batch', uom:'uom', pkg:'pkg', expiry:'expiry', category:'category', sap:'sap', cnt:'cnt', dmg:'dmg', exp:'expQty', by:'assignedTo', whcode:'wh', binloc:'warehouse', pair:'assignedTo', src:'itemStatus', status:'dropped' },
  newItems: [],
  pairs: [],
  selItems: new Set(),
  openPairId: null,
  repairPairId: null,
  repReplName: null,
  repReplInit: null,
  editWarehousePairId: null,
  editPairId: null,
  nextPair: 5,
  curSessId: null,
  editSessId: null,
  lastCheckedRow: null,
  countSessId: localStorage.getItem('stp_count_sess') || null,
  countItems: [],
  countPairId: null,
  _countWhFilter: '',
  ssoEmailPending: '',
  SSO_USER_KEY: 'stp_sso_user',
  SSO_EMAIL_KEY: 'stp_sso_email',
  ssoUserName: sessionStorage.getItem('SSO_USER_KEY') || sessionStorage.getItem('stp_sso_user') || '',
  ssoUserEmail: sessionStorage.getItem('SSO_EMAIL_KEY') || sessionStorage.getItem('stp_sso_email') || '',
  ssoUserRole: sessionStorage.getItem('stp_sso_role') || 'User',
  SSO_ROLE_KEY: 'stp_sso_role',
  STATUS_DRAFT: 'Draft',
  STATUS_ACTIVE: 'Active',
  STATUS_CLOSED: 'Closed',
  ROLE_ADMIN: 'Admin',
  ROLE_USER: 'User'
};
